### ISSUE TITLE
クラウド版r.5405でサーバー配信を1時間単位で定期実行可能機能が表示されていない可能性があります

### ISSUE THREAD

**Issue by madeinharu** [movabletype/mt-plugin-periodic-sync#9]
お世話になります。MT7クラウド版を利用しており、PeriodicSync プラグインを活用させていただいております。
https://gyazo.com/a0f2487e8137e7328458c2559517fd7d
定期実行可能機能が表示されておらず、
機能の位置が異なる可能性もありますが、アドバイスいただくことは可能でしょうか。

どうぞよろしくお願い致します。

**Comment by usualoma** [comment]
@madeinharu フィードバックありがとうございます。

ご不便をおかけして申し訳ありません。 Movable Typeの本体側の更新により、定期実行のオプションが表示されない状態になっています。Movable Typeの次のリリースで修正される予定です。

**Comment by madeinharu** [comment]
@usualoma さっそくのご返答ありがとうございます。上記の旨承知致しました。メーカー側に時期アップデートタイミングをお伺いしてみます。ありがとうございました。
